codecov:
  notify:
    require_ci_to_pass: yes

coverage:
  precision: 2
  round: down
  range: "70...100"

  status:
    project: yes
    patch: yes
    changes: no

comment:
  layout: "reach, diff, flags, files, footer"
  behavior: default
require_changes: no

ignore:
  - "opentimelineio_contrib/adapters/tests/test_rvsession.py"
  - "opentimelineio_contrib/adapters/tests/test_maya_sequencer.py"
  - "opentimelineio_contrib/adapters/tests/test_burnins.py"
  - "opentimelineio_contrib/adapters/burnins.py"
