codecov:
  notify: {}
  require_ci_to_pass: yes

coverage:
  precision: 2
  round: down
  range: "70...95"

  status:
    project: yes
    patch: yes
    changes: yes

comment:
  layout: "reach, diff, flags, files, footer"
  behavior: default
  require_changes: no

ignore:
  - "contrib/opentimelineio_contrib/adapters/tests/test_rvsession.py"
  - "*aaf2*"
  - "*pkg_resources*"
  - "*pbr*"
  - "*mock*"
  - "*PIL*"
  - "*funcsigs*"
  - "/usr/*"
  - "*/deps/*"
