#!/usr/bin/env python
#
# SPDX-License-Identifier: Apache-2.0
# Copyright Contributors to the OpenTimelineIO project


"""Generates documentation of the serialized data model for OpenTimelineIO."""

import argparse
import inspect
import json
import re
import tempfile
import sys
import textwrap

import io

import opentimelineio as otio


DOCUMENT_HEADER = """# Serialized Data Documentation

This documents all the OpenTimelineIO classes that serialize to and from JSON,
omitting SchemaDef plugins. This document is automatically generated by
running:

`src/py-opentimelineio/opentimelineio/console/autogen_serialized_datamodel.py`

or by running:

`make doc-model`

It is part of the unit tests suite and should be updated whenever the schema
changes.  If it needs to be updated and this file regenerated, run:

`make doc-model-update`

# Class Documentation

"""

FIELDS_ONLY_HEADER = """# Serialized Data (Fields Only)

This document is a list of all the OpenTimelineIO classes that serialize to and
from JSON, omitting plugins classes and docstrings.

This document is automatically generated by running:

`src/py-opentimelineio/opentimelineio/console/autogen_serialized_datamodel.py`

or by running:

`make doc-model`

It is part of the unit tests suite and should be updated whenever the schema
changes.  If it needs to be updated and this file regenerated, run:

`make doc-model-update`


# Classes

"""

CLASS_HEADER_WITH_DOCS = """
### {classname}

*full module path*: `{modpath}`
{inheritance}
*documentation*:

```
{docstring}
```

parameters:
"""

CLASS_HEADER_ONLY_FIELDS = """
### {classname}

parameters:
"""

MODULE_HEADER = """
## Module: {modname}
"""

PROP_HEADER = """- *{propkey}*{typeinfo}: {prophelp}
"""

PROP_HEADER_NO_HELP = """- *{propkey}*{typeinfo}
"""

# three ways to try and get the property + docstring
PROP_FETCHERS = (
    lambda cl, k: inspect.getdoc(getattr(cl, k)),
    lambda cl, k: inspect.getdoc(getattr(cl, "_" + k)),
    lambda cl, k: inspect.getdoc(getattr(cl(), k)) and "" or "",
)

# pybind11 prefixes the C++ module onto every type it reports; strip them so the
# documentation reads in terms of the public python schema.
_TYPE_MODULE_PREFIXES = (
    "opentimelineio._opentime.",
    "opentimelineio._otio.",
    "_opentime.",
    "_otio.",
    "opentimelineio.",
)

# map pybind11/python primitive spellings onto the vocabulary used by the OTIO
# Core Specification.
_PRIMITIVE_REMAP = {
    "str": "String",
    "float": "Double",
    "int": "Integer",
    "bool": "Boolean",
    "object": None,  # the `any`-backed fields report `object`; infer from value
}


def _clean_type(type_str):
    """Strip the internal C++ module prefixes off a pybind11 type string."""
    for prefix in _TYPE_MODULE_PREFIXES:
        type_str = type_str.replace(prefix, "")
    return type_str.strip()


def _type_from_value(value):
    """Infer a spec-style type name from a serialized default value.

    Used as a fallback when the property's signature does not advertise a usable
    return type (e.g. the metadata-backed `any` fields, which report `object`).
    """
    # bool must be checked before int, since bool is a subclass of int
    if isinstance(value, bool):
        return "Boolean"
    if isinstance(value, int):
        return "Integer"
    if isinstance(value, float):
        return "Double"
    if isinstance(value, str):
        return "String"
    if isinstance(value, list):
        return "Array"
    if isinstance(value, dict):
        if "OTIO_SCHEMA" in value:
            return value["OTIO_SCHEMA"].rsplit(".", 1)[0]
        return "Map"
    return None


def _normalize_type(raw):
    """Turn a raw pybind11 return-type string into a (type, optional) pair.

    Examples:
        ``Optional[...TimeRange]``      -> ("TimeRange", True)
        ``...EffectVector``             -> ("Array[Effect]", False)
        ``dict[str, ...MediaReference]``-> ("Map[String, MediaReference]", False)
        ``AnyDictionary``               -> ("Map[String, Any]", False)
        ``float``                       -> ("Double", False)
    """
    type_str = _clean_type(raw)

    optional = False
    opt = re.match(r"Optional\[(.*)\]$", type_str)
    if opt:
        optional = True
        type_str = opt.group(1).strip()

    vec = re.match(r"(.+)Vector$", type_str)
    dct = re.match(r"[Dd]ict\[\s*str\s*,\s*(.+)\]$", type_str)
    if vec:
        inner = vec.group(1)
        type_str = "Array[{}]".format(_PRIMITIVE_REMAP.get(inner, inner) or inner)
    elif type_str == "AnyDictionary":
        type_str = "Map[String, Any]"
    elif dct:
        inner = dct.group(1).strip()
        type_str = "Map[String, {}]".format(
            _PRIMITIVE_REMAP.get(inner, inner) or inner
        )
    elif type_str in _PRIMITIVE_REMAP:
        type_str = _PRIMITIVE_REMAP[type_str]

    return type_str, optional


def _signature_return_type(cl, key):
    """Return the raw pybind11 return-type annotation for a field, if any.

    pybind11 records the C++ type signature in the docstring of a property's
    getter (``fget``) or of a plain method (e.g. ``media_references``).
    """
    try:
        attr = getattr(cl, key)
    except AttributeError:
        return None

    doc = None
    fget = getattr(attr, "fget", None)
    if fget is not None:
        doc = inspect.getdoc(fget)
    elif callable(attr):
        doc = inspect.getdoc(attr)

    if doc and "->" in doc:
        return doc.rsplit("->", 1)[-1].strip()
    return None


def _type_for_property(cl, key, value):
    """Resolve the (type, optional) pair for a serialized field.

    Prefers the type advertised by the pybind11 signature, falling back to
    inferring from the serialized default value when the signature is missing or
    opaque (``object``).
    """
    raw = _signature_return_type(cl, key)
    if raw is not None:
        type_str, optional = _normalize_type(raw)
        if type_str:
            return type_str, optional

    # fall back to inferring from the serialized default value
    return _type_from_value(value), value is None


def _inheritance_chain(cl):
    """The list of schema base-class names a class derives from, most-derived
    first. Empty for types outside the SerializableObject hierarchy (e.g.
    RationalTime, TimeRange, Color)."""
    return [
        base.__name__
        for base in inspect.getmro(cl)[1:]
        if base.__name__ not in ("object", "pybind11_object")
    ]


def _default_repr(value):
    """A compact JSON rendering of a default value, or None when it should be
    omitted (null values and large/composite defaults that would add noise)."""
    if value is None:
        return None
    try:
        rendered = json.dumps(value)
    except (TypeError, ValueError):
        return None
    if len(rendered) > 40:
        return None
    return rendered


def _format_typeinfo(entry, include_default):
    """Render the parenthetical ``(`Type`, optional, default: `x`)`` annotation
    for a property, or "" when the type could not be resolved (e.g. plugin
    fields with no signature and a null default)."""
    if not entry["type"]:
        return ""
    parts = ["`{}`".format(entry["type"])]
    if entry["optional"]:
        parts.append("optional")
    if include_default:
        default = _default_repr(entry["default"])
        if default is not None:
            parts.append("default: `{}`".format(default))
    if not parts:
        return ""
    return " ({})".format(", ".join(parts))


def _parsed_args():
    """ parse commandline arguments with argparse """

    parser = argparse.ArgumentParser(
        description=__doc__,
        formatter_class=argparse.ArgumentDefaultsHelpFormatter
    )
    group = parser.add_mutually_exclusive_group()
    group.add_argument(
        "-d",
        "--dryrun",
        action="store_true",
        default=False,
        help="Dryrun mode - print out instead of perform actions"
    )
    group.add_argument(
        "-o",
        "--output",
        type=str,
        default=None,
        help="Update the baseline with the current version"
    )

    return parser.parse_args()


# things to skip.  These are typically internal/private classes that don't need
# to be considered "Public Schema".
SKIP_CLASSES = [
    otio.core.SerializableObject,
    otio._otio.UnknownSchema,
    otio._otio.TestObject,
]
SKIP_KEYS = [
    "OTIO_SCHEMA",  # not data, just for the backing format
    "children",     # children are stored by container objects, implicitly
]
SKIP_MODULES = [
    "opentimelineio.schemadef",  # because these are plugins
    "opentimelineio._otio",      # C++ .so, but customers should use the full
    "opentimelineio._opentime",  # python wrapped modules (otio.schema etc)
]


def _generate_model_for_module(mod, classes, modules):
    modules.add(mod)

    # fetch the classes from this module
    serializable_classes = [
        thing for thing in mod.__dict__.values()
        if (
            inspect.isclass(thing)
            and thing not in classes
            and issubclass(thing, otio.core.SerializableObject)
            or thing in (
                otio.opentime.RationalTime,
                otio.opentime.TimeRange,
                otio.opentime.TimeTransform,
                otio.core.Color
            )
        )
    ]

    # serialize/deserialize the classes to capture their serialized parameters
    model = {}
    for cl in serializable_classes:
        if cl in SKIP_CLASSES:
            continue

        model[cl] = {}
        field_dict = json.loads(otio.adapters.otio_json.write_to_string(cl()))
        for k in field_dict.keys():
            if k in SKIP_KEYS:
                continue

            value = field_dict[k]
            helpstr = ""
            for fetcher in PROP_FETCHERS:
                try:
                    # Serialized fields are almost always properties, but skip
                    # over those that are not
                    helpstr = fetcher(cl, k) if isinstance(
                        getattr(cl, k), property) else ""
                    break
                except AttributeError:
                    pass
            else:
                sys.stderr.write(f"ERROR: could not fetch property: {k}")

            type_str, optional = _type_for_property(cl, k, value)
            model[cl][k] = {
                "help": helpstr or "",
                "type": type_str,
                "optional": optional,
                "default": value,
            }

        # Stashing the OTIO_SCHEMA back into the dictionary since the
        # documentation uses this information in its header.
        model[cl]["OTIO_SCHEMA"] = field_dict["OTIO_SCHEMA"]

    classes.update(model)

    # find new modules to recurse into
    new_mods = sorted(
        (
            thing for thing in mod.__dict__.values()
            if (
                inspect.ismodule(thing)
                and thing not in modules
                and "opentimelineio" in thing.__name__
                and all(not thing.__name__.startswith(t) for t in SKIP_MODULES)
            )
        ),
        key=lambda mod: str(mod)
    )

    # recurse into the new modules and update the classes and modules values
    [_generate_model_for_module(m, classes, modules) for m in new_mods]


def _generate_model():
    classes = {}
    modules = set()
    _generate_model_for_module(otio, classes, modules)
    return classes


def _search_mod_recursively(cl, mod_to_search, already_searched):
    if cl in mod_to_search.__dict__.values():
        return mod_to_search.__name__

    child_modules = (
        m
        for m in mod_to_search.__dict__.values()
        if inspect.ismodule(m)
    )

    for submod in child_modules:
        if submod in already_searched:
            continue
        already_searched.add(submod)
        result = _search_mod_recursively(cl, submod, already_searched)
        if result is not None:
            return result

    return None


def _remap_to_python_modules(cl):
    """Find the module containing the python wrapped class, rather than the base
    C++ _otio modules.
    """

    # where the python wrapped classes live
    SEARCH_MODULES = [
        otio.schema,
        otio.opentime,
        otio.core,
    ]

    # the C++ modules
    IGNORE_MODS = {
        otio._otio,
        otio._opentime
    }

    for mod in SEARCH_MODULES:
        result = _search_mod_recursively(cl, mod, IGNORE_MODS)
        if result is not None:
            return result

    return inspect.getmodule(cl).__name__


def _write_documentation(model):
    md_with_helpstrings = io.StringIO()
    md_only_fields = io.StringIO()

    md_with_helpstrings.write(DOCUMENT_HEADER)
    md_only_fields.write(FIELDS_ONLY_HEADER)

    modules = {}
    for cl in model:
        modobj = cl.__module__

        if modobj in ['opentimelineio._opentime', 'opentimelineio._otio']:
            modobj = _remap_to_python_modules(cl)

        modules.setdefault(modobj, []).append(cl)

    CURRENT_MODULE = None
    for module_list in sorted(modules):
        this_mod = ".".join(module_list.split('.')[:2])
        if this_mod != CURRENT_MODULE:
            CURRENT_MODULE = this_mod
            md_with_helpstrings.write(MODULE_HEADER.format(modname=this_mod))
            md_only_fields.write(MODULE_HEADER.format(modname=this_mod))

        # because these are classes, they need to sort on their stringified
        # names
        for cl in sorted(modules[module_list], key=lambda cl: str(cl)):
            modname = this_mod
            label = model[cl]["OTIO_SCHEMA"]

            if (cl.__doc__ is not None):
                docstring = inspect.getdoc(cl).split("\n")
                new_docstring = []
                for line in docstring:
                    line = textwrap.wrap(line, width=100,
                                         expand_tabs=False,
                                         replace_whitespace=False,
                                         drop_whitespace=False,
                                         break_long_words=False)
                    if (line == []):
                        line = [""]
                    for wrapped_line in line:
                        new_docstring.append(wrapped_line)
                new_docstring = "\n".join(new_docstring)
            else:
                new_docstring = cl.__doc__

            chain = _inheritance_chain(cl)
            if chain:
                inheritance = "\n*inherits from*: {}\n".format(
                    " -> ".join("`{}`".format(name) for name in chain)
                )
            else:
                inheritance = ""

            md_with_helpstrings.write(
                CLASS_HEADER_WITH_DOCS.format(
                    classname=label,
                    modpath=modname + "." + cl.__name__,
                    inheritance=inheritance,
                    docstring=new_docstring
                )
            )
            md_only_fields.write(
                CLASS_HEADER_ONLY_FIELDS.format(
                    classname=label,
                )
            )

            for key, entry in sorted(model[cl].items()):
                if key in SKIP_KEYS:
                    continue
                md_with_helpstrings.write(
                    PROP_HEADER.format(
                        propkey=key,
                        typeinfo=_format_typeinfo(entry, include_default=True),
                        prophelp=entry["help"],
                    )
                )
                md_only_fields.write(
                    PROP_HEADER_NO_HELP.format(
                        propkey=key,
                        typeinfo=_format_typeinfo(entry, include_default=False),
                    )
                )

    return md_with_helpstrings.getvalue(), md_only_fields.getvalue()


def main():
    """  main entry point  """
    args = _parsed_args()
    with_docs, without_docs = generate_and_write_documentation()

    # print it out somewhere
    if args.dryrun:
        print(with_docs)
        return

    output = args.output
    if not output:
        output = tempfile.NamedTemporaryFile(
            'w',
            suffix="otio_serialized_schema.md",
            delete=False
        ).name

    with open(output, 'w') as fo:
        fo.write(with_docs)

    # write version without docstrings
    prefix, suffix = output.rsplit('.', 1)
    output_only_fields = prefix + "-only-fields." + suffix

    with open(output_only_fields, 'w') as fo:
        fo.write(without_docs)

    print(f"wrote documentation to {output} and {output_only_fields}")


def generate_and_write_documentation():
    model = _generate_model()
    return _write_documentation(model)


if __name__ == '__main__':
    main()
