// SPDX-License-Identifier: Apache-2.0
// Copyright Contributors to the OpenTimelineIO project
//
// This document is automatically generated by running the
// `autogen_version_info` command, or by running `make version-info`.  It is
// part of the unit tests suite and should be updated whenever schema versions
// change.  If it needs to be updated, run: `make version-info-update` and this
// file should be regenerated.
//
// This is a mapping of "family" to "label", where each label is then mapped to
// a "schema-version map", a mapping of schema name to schema version for that
// label.
#include "opentimelineio/typeRegistry.h"

namespace opentimelineio { namespace OPENTIMELINEIO_VERSION {

const label_to_schema_version_map CORE_VERSION_MAP {
    // {next}
};

} } // namespace opentimelineio::OPENTIMELINEIO_VERSION
