// SPDX-License-Identifier: Apache-2.0
// Copyright Contributors to the OpenTimelineIO project
//
// This document is automatically generated by running the `make version-map`
// make target.  It is part of the unit tests suite and should be updated
// whenever schema versions change.  If it needs to be updated, run: `make
// version-map-update` and this file should be regenerated.
//
// This maps a "Label" to a map of Schema name to Schema version. The intent is
// that these sets of schemas can be used for compatability with future
// versions of OTIO, so that a newer version of OTIO can target a compatability
// version of an older library.
#include "opentimelineio/typeRegistry.h"

namespace opentimelineio { namespace OPENTIMELINEIO_VERSION {

const label_to_schema_version_map CORE_VERSION_MAP {
    // {next}
};

} } // namespace opentimelineio::OPENTIMELINEIO_VERSION
