/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package io.opentimeline;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }

    public native void print();

    static {
        if (!LibraryLoader.load(Library.class, "jotio"))
            System.loadLibrary("jotio");
    }
}
