/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_opentimeline_opentimelineio_AnyVector */

#ifndef _Included_io_opentimeline_opentimelineio_AnyVector
#define _Included_io_opentimeline_opentimelineio_AnyVector
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io_opentimeline_opentimelineio_AnyVector
 * Method:    initialize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_io_opentimeline_opentimelineio_AnyVector_initialize
  (JNIEnv *, jobject);

/*
 * Class:     io_opentimeline_opentimelineio_AnyVector
 * Method:    getArray
 * Signature: ()[Lio/opentimeline/opentimelineio/Any;
 */
JNIEXPORT jobjectArray JNICALL Java_io_opentimeline_opentimelineio_AnyVector_getArray
  (JNIEnv *, jobject);

/*
 * Class:     io_opentimeline_opentimelineio_AnyVector
 * Method:    get
 * Signature: (I)Lio/opentimeline/opentimelineio/Any;
 */
JNIEXPORT jobject JNICALL Java_io_opentimeline_opentimelineio_AnyVector_get
  (JNIEnv *, jobject, jint);

/*
 * Class:     io_opentimeline_opentimelineio_AnyVector
 * Method:    add
 * Signature: (Lio/opentimeline/opentimelineio/Any;)Z
 */
JNIEXPORT jboolean JNICALL Java_io_opentimeline_opentimelineio_AnyVector_add__Lio_opentimeline_opentimelineio_Any_2
  (JNIEnv *, jobject, jobject);

/*
 * Class:     io_opentimeline_opentimelineio_AnyVector
 * Method:    add
 * Signature: (ILio/opentimeline/opentimelineio/Any;)Z
 */
JNIEXPORT jboolean JNICALL Java_io_opentimeline_opentimelineio_AnyVector_add__ILio_opentimeline_opentimelineio_Any_2
  (JNIEnv *, jobject, jint, jobject);

/*
 * Class:     io_opentimeline_opentimelineio_AnyVector
 * Method:    clear
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_io_opentimeline_opentimelineio_AnyVector_clear
  (JNIEnv *, jobject);

/*
 * Class:     io_opentimeline_opentimelineio_AnyVector
 * Method:    ensureCapacity
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_io_opentimeline_opentimelineio_AnyVector_ensureCapacity
  (JNIEnv *, jobject, jint);

/*
 * Class:     io_opentimeline_opentimelineio_AnyVector
 * Method:    size
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_io_opentimeline_opentimelineio_AnyVector_size
  (JNIEnv *, jobject);

/*
 * Class:     io_opentimeline_opentimelineio_AnyVector
 * Method:    remove
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_io_opentimeline_opentimelineio_AnyVector_remove
  (JNIEnv *, jobject, jint);

/*
 * Class:     io_opentimeline_opentimelineio_AnyVector
 * Method:    trimToSize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_io_opentimeline_opentimelineio_AnyVector_trimToSize
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
