/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_opentimeline_OTIONative */

#ifndef _Included_io_opentimeline_OTIONative
#define _Included_io_opentimeline_OTIONative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io_opentimeline_OTIONative
 * Method:    getOTIOObjectNativeHandle
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_io_opentimeline_OTIONative_getOTIOObjectNativeHandle
  (JNIEnv *, jobject);

/*
 * Class:     io_opentimeline_OTIONative
 * Method:    close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_io_opentimeline_OTIONative_close
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
