/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_opentimeline_opentimelineio_Serialization */

#ifndef _Included_io_opentimeline_opentimelineio_Serialization
#define _Included_io_opentimeline_opentimelineio_Serialization
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io_opentimeline_opentimelineio_Serialization
 * Method:    serializeJSONToStringNative
 * Signature: (Lio/opentimeline/opentimelineio/Any;Lio/opentimeline/opentimelineio/ErrorStatus;I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_io_opentimeline_opentimelineio_Serialization_serializeJSONToStringNative
  (JNIEnv *, jclass, jobject, jobject, jint);

/*
 * Class:     io_opentimeline_opentimelineio_Serialization
 * Method:    serializeJSONToFileNative
 * Signature: (Lio/opentimeline/opentimelineio/Any;Ljava/lang/String;Lio/opentimeline/opentimelineio/ErrorStatus;I)Z
 */
JNIEXPORT jboolean JNICALL Java_io_opentimeline_opentimelineio_Serialization_serializeJSONToFileNative
  (JNIEnv *, jclass, jobject, jstring, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
