/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_opentimeline_opentimelineio_Gap */

#ifndef _Included_io_opentimeline_opentimelineio_Gap
#define _Included_io_opentimeline_opentimelineio_Gap
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io_opentimeline_opentimelineio_Gap
 * Method:    initializeSourceRange
 * Signature: ([DLjava/lang/String;[Lio/opentimeline/opentimelineio/Effect;[Lio/opentimeline/opentimelineio/Marker;Lio/opentimeline/opentimelineio/AnyDictionary;)V
 */
JNIEXPORT void JNICALL Java_io_opentimeline_opentimelineio_Gap_initializeSourceRange
  (JNIEnv *, jobject, jdoubleArray, jstring, jobjectArray, jobjectArray, jobject);

/*
 * Class:     io_opentimeline_opentimelineio_Gap
 * Method:    initializeDuration
 * Signature: ([DLjava/lang/String;[Lio/opentimeline/opentimelineio/Effect;[Lio/opentimeline/opentimelineio/Marker;Lio/opentimeline/opentimelineio/AnyDictionary;)V
 */
JNIEXPORT void JNICALL Java_io_opentimeline_opentimelineio_Gap_initializeDuration
  (JNIEnv *, jobject, jdoubleArray, jstring, jobjectArray, jobjectArray, jobject);

/*
 * Class:     io_opentimeline_opentimelineio_Gap
 * Method:    isVisible
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_io_opentimeline_opentimelineio_Gap_isVisible
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
