/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_opentimeline_opentimelineio_ImageSequenceReference */

#ifndef _Included_io_opentimeline_opentimelineio_ImageSequenceReference
#define _Included_io_opentimeline_opentimelineio_ImageSequenceReference
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io_opentimeline_opentimelineio_ImageSequenceReference
 * Method:    initialize
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;IIDIILio/opentimeline/opentime/TimeRange;Lio/opentimeline/opentimelineio/AnyDictionary;)V
 */
JNIEXPORT void JNICALL Java_io_opentimeline_opentimelineio_ImageSequenceReference_initialize
  (JNIEnv *, jobject, jstring, jstring, jstring, jint, jint, jdouble, jint, jint, jobject, jobject);

/*
 * Class:     io_opentimeline_opentimelineio_ImageSequenceReference
 * Method:    getTargetURLBase
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_io_opentimeline_opentimelineio_ImageSequenceReference_getTargetURLBase
  (JNIEnv *, jobject);

/*
 * Class:     io_opentimeline_opentimelineio_ImageSequenceReference
 * Method:    setTargetURLBase
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_io_opentimeline_opentimelineio_ImageSequenceReference_setTargetURLBase
  (JNIEnv *, jobject, jstring);

/*
 * Class:     io_opentimeline_opentimelineio_ImageSequenceReference
 * Method:    getNamePrefix
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_io_opentimeline_opentimelineio_ImageSequenceReference_getNamePrefix
  (JNIEnv *, jobject);

/*
 * Class:     io_opentimeline_opentimelineio_ImageSequenceReference
 * Method:    setNamePrefix
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_io_opentimeline_opentimelineio_ImageSequenceReference_setNamePrefix
  (JNIEnv *, jobject, jstring);

/*
 * Class:     io_opentimeline_opentimelineio_ImageSequenceReference
 * Method:    getNameSuffix
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_io_opentimeline_opentimelineio_ImageSequenceReference_getNameSuffix
  (JNIEnv *, jobject);

/*
 * Class:     io_opentimeline_opentimelineio_ImageSequenceReference
 * Method:    setNameSuffix
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_io_opentimeline_opentimelineio_ImageSequenceReference_setNameSuffix
  (JNIEnv *, jobject, jstring);

/*
 * Class:     io_opentimeline_opentimelineio_ImageSequenceReference
 * Method:    getStartFrame
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_io_opentimeline_opentimelineio_ImageSequenceReference_getStartFrame
  (JNIEnv *, jobject);

/*
 * Class:     io_opentimeline_opentimelineio_ImageSequenceReference
 * Method:    setStartFrame
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_io_opentimeline_opentimelineio_ImageSequenceReference_setStartFrame
  (JNIEnv *, jobject, jint);

/*
 * Class:     io_opentimeline_opentimelineio_ImageSequenceReference
 * Method:    getFrameStep
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_io_opentimeline_opentimelineio_ImageSequenceReference_getFrameStep
  (JNIEnv *, jobject);

/*
 * Class:     io_opentimeline_opentimelineio_ImageSequenceReference
 * Method:    setFrameStep
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_io_opentimeline_opentimelineio_ImageSequenceReference_setFrameStep
  (JNIEnv *, jobject, jint);

/*
 * Class:     io_opentimeline_opentimelineio_ImageSequenceReference
 * Method:    getRate
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_io_opentimeline_opentimelineio_ImageSequenceReference_getRate
  (JNIEnv *, jobject);

/*
 * Class:     io_opentimeline_opentimelineio_ImageSequenceReference
 * Method:    setRate
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_io_opentimeline_opentimelineio_ImageSequenceReference_setRate
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     io_opentimeline_opentimelineio_ImageSequenceReference
 * Method:    getFrameZeroPadding
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_io_opentimeline_opentimelineio_ImageSequenceReference_getFrameZeroPadding
  (JNIEnv *, jobject);

/*
 * Class:     io_opentimeline_opentimelineio_ImageSequenceReference
 * Method:    setFrameZeroPadding
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_io_opentimeline_opentimelineio_ImageSequenceReference_setFrameZeroPadding
  (JNIEnv *, jobject, jint);

/*
 * Class:     io_opentimeline_opentimelineio_ImageSequenceReference
 * Method:    getMissingFramePolicyNative
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_io_opentimeline_opentimelineio_ImageSequenceReference_getMissingFramePolicyNative
  (JNIEnv *, jobject);

/*
 * Class:     io_opentimeline_opentimelineio_ImageSequenceReference
 * Method:    setMissingFramePolicyNative
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_io_opentimeline_opentimelineio_ImageSequenceReference_setMissingFramePolicyNative
  (JNIEnv *, jobject, jint);

/*
 * Class:     io_opentimeline_opentimelineio_ImageSequenceReference
 * Method:    getEndFrame
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_io_opentimeline_opentimelineio_ImageSequenceReference_getEndFrame
  (JNIEnv *, jobject);

/*
 * Class:     io_opentimeline_opentimelineio_ImageSequenceReference
 * Method:    getNumberOfImagesInSequence
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_io_opentimeline_opentimelineio_ImageSequenceReference_getNumberOfImagesInSequence
  (JNIEnv *, jobject);

/*
 * Class:     io_opentimeline_opentimelineio_ImageSequenceReference
 * Method:    getFrameForTime
 * Signature: (Lio/opentimeline/opentime/RationalTime;Lio/opentimeline/opentimelineio/ErrorStatus;)I
 */
JNIEXPORT jint JNICALL Java_io_opentimeline_opentimelineio_ImageSequenceReference_getFrameForTime
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     io_opentimeline_opentimelineio_ImageSequenceReference
 * Method:    getTargetURLForImageNumber
 * Signature: (ILio/opentimeline/opentimelineio/ErrorStatus;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_io_opentimeline_opentimelineio_ImageSequenceReference_getTargetURLForImageNumber
  (JNIEnv *, jobject, jint, jobject);

/*
 * Class:     io_opentimeline_opentimelineio_ImageSequenceReference
 * Method:    presentationTimeForImageNumber
 * Signature: (ILio/opentimeline/opentimelineio/ErrorStatus;)Lio/opentimeline/opentime/RationalTime;
 */
JNIEXPORT jobject JNICALL Java_io_opentimeline_opentimelineio_ImageSequenceReference_presentationTimeForImageNumber
  (JNIEnv *, jobject, jint, jobject);

#ifdef __cplusplus
}
#endif
#endif
