/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_opentimeline_Library */

#ifndef _Included_io_opentimeline_Library
#define _Included_io_opentimeline_Library
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io_opentimeline_Library
 * Method:    print
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_io_opentimeline_Library_print
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
