/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_opentimeline_opentimelineio_ErrorStatus */

#ifndef _Included_io_opentimeline_opentimelineio_ErrorStatus
#define _Included_io_opentimeline_opentimelineio_ErrorStatus
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io_opentimeline_opentimelineio_ErrorStatus
 * Method:    initialize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_io_opentimeline_opentimelineio_ErrorStatus_initialize
  (JNIEnv *, jobject);

/*
 * Class:     io_opentimeline_opentimelineio_ErrorStatus
 * Method:    outcomeToStringNative
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_io_opentimeline_opentimelineio_ErrorStatus_outcomeToStringNative
  (JNIEnv *, jclass, jint);

/*
 * Class:     io_opentimeline_opentimelineio_ErrorStatus
 * Method:    getOutcomeNative
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_io_opentimeline_opentimelineio_ErrorStatus_getOutcomeNative
  (JNIEnv *, jobject);

/*
 * Class:     io_opentimeline_opentimelineio_ErrorStatus
 * Method:    dispose
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_io_opentimeline_opentimelineio_ErrorStatus_dispose
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
