/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_opentimeline_opentimelineio_MissingReference */

#ifndef _Included_io_opentimeline_opentimelineio_MissingReference
#define _Included_io_opentimeline_opentimelineio_MissingReference
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io_opentimeline_opentimelineio_MissingReference
 * Method:    initialize
 * Signature: (Ljava/lang/String;[DLio/opentimeline/opentimelineio/AnyDictionary;)V
 */
JNIEXPORT void JNICALL Java_io_opentimeline_opentimelineio_MissingReference_initialize
  (JNIEnv *, jobject, jstring, jdoubleArray, jobject);

/*
 * Class:     io_opentimeline_opentimelineio_MissingReference
 * Method:    isMissingReference
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_io_opentimeline_opentimelineio_MissingReference_isMissingReference
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
