/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_opentimeline_opentimelineio_Transition */

#ifndef _Included_io_opentimeline_opentimelineio_Transition
#define _Included_io_opentimeline_opentimelineio_Transition
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io_opentimeline_opentimelineio_Transition
 * Method:    initialize
 * Signature: (Ljava/lang/String;Ljava/lang/String;Lio/opentimeline/opentime/RationalTime;Lio/opentimeline/opentime/RationalTime;Lio/opentimeline/opentimelineio/AnyDictionary;)V
 */
JNIEXPORT void JNICALL Java_io_opentimeline_opentimelineio_Transition_initialize
  (JNIEnv *, jobject, jstring, jstring, jobject, jobject, jobject);

/*
 * Class:     io_opentimeline_opentimelineio_Transition
 * Method:    isOverlapping
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_io_opentimeline_opentimelineio_Transition_isOverlapping
  (JNIEnv *, jobject);

/*
 * Class:     io_opentimeline_opentimelineio_Transition
 * Method:    getTransitionType
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_io_opentimeline_opentimelineio_Transition_getTransitionType
  (JNIEnv *, jobject);

/*
 * Class:     io_opentimeline_opentimelineio_Transition
 * Method:    setTransitionType
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_io_opentimeline_opentimelineio_Transition_setTransitionType
  (JNIEnv *, jobject, jstring);

/*
 * Class:     io_opentimeline_opentimelineio_Transition
 * Method:    getInOffset
 * Signature: ()Lio/opentimeline/opentime/RationalTime;
 */
JNIEXPORT jobject JNICALL Java_io_opentimeline_opentimelineio_Transition_getInOffset
  (JNIEnv *, jobject);

/*
 * Class:     io_opentimeline_opentimelineio_Transition
 * Method:    setInOffset
 * Signature: (Lio/opentimeline/opentime/RationalTime;)V
 */
JNIEXPORT void JNICALL Java_io_opentimeline_opentimelineio_Transition_setInOffset
  (JNIEnv *, jobject, jobject);

/*
 * Class:     io_opentimeline_opentimelineio_Transition
 * Method:    getOutOffset
 * Signature: ()Lio/opentimeline/opentime/RationalTime;
 */
JNIEXPORT jobject JNICALL Java_io_opentimeline_opentimelineio_Transition_getOutOffset
  (JNIEnv *, jobject);

/*
 * Class:     io_opentimeline_opentimelineio_Transition
 * Method:    setOutOffset
 * Signature: (Lio/opentimeline/opentime/RationalTime;)V
 */
JNIEXPORT void JNICALL Java_io_opentimeline_opentimelineio_Transition_setOutOffset
  (JNIEnv *, jobject, jobject);

/*
 * Class:     io_opentimeline_opentimelineio_Transition
 * Method:    getDuration
 * Signature: (Lio/opentimeline/opentimelineio/ErrorStatus;)Lio/opentimeline/opentime/RationalTime;
 */
JNIEXPORT jobject JNICALL Java_io_opentimeline_opentimelineio_Transition_getDuration
  (JNIEnv *, jobject, jobject);

/*
 * Class:     io_opentimeline_opentimelineio_Transition
 * Method:    getRangeInParent
 * Signature: (Lio/opentimeline/opentimelineio/ErrorStatus;)Lio/opentimeline/opentime/TimeRange;
 */
JNIEXPORT jobject JNICALL Java_io_opentimeline_opentimelineio_Transition_getRangeInParent
  (JNIEnv *, jobject, jobject);

/*
 * Class:     io_opentimeline_opentimelineio_Transition
 * Method:    getTrimmedRangeInParent
 * Signature: (Lio/opentimeline/opentimelineio/ErrorStatus;)Lio/opentimeline/opentime/TimeRange;
 */
JNIEXPORT jobject JNICALL Java_io_opentimeline_opentimelineio_Transition_getTrimmedRangeInParent
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
