/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_opentimeline_opentimelineio_LinearTimeWarp */

#ifndef _Included_io_opentimeline_opentimelineio_LinearTimeWarp
#define _Included_io_opentimeline_opentimelineio_LinearTimeWarp
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io_opentimeline_opentimelineio_LinearTimeWarp
 * Method:    initialize
 * Signature: (Ljava/lang/String;Ljava/lang/String;DLio/opentimeline/opentimelineio/AnyDictionary;)V
 */
JNIEXPORT void JNICALL Java_io_opentimeline_opentimelineio_LinearTimeWarp_initialize
  (JNIEnv *, jobject, jstring, jstring, jdouble, jobject);

/*
 * Class:     io_opentimeline_opentimelineio_LinearTimeWarp
 * Method:    getTimeScalar
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_io_opentimeline_opentimelineio_LinearTimeWarp_getTimeScalar
  (JNIEnv *, jobject);

/*
 * Class:     io_opentimeline_opentimelineio_LinearTimeWarp
 * Method:    setTimeScalar
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_io_opentimeline_opentimelineio_LinearTimeWarp_setTimeScalar
  (JNIEnv *, jobject, jdouble);

#ifdef __cplusplus
}
#endif
#endif
