/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_opentimeline_opentimelineio_UnknownSchema */

#ifndef _Included_io_opentimeline_opentimelineio_UnknownSchema
#define _Included_io_opentimeline_opentimelineio_UnknownSchema
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io_opentimeline_opentimelineio_UnknownSchema
 * Method:    initialize
 * Signature: (Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_io_opentimeline_opentimelineio_UnknownSchema_initialize
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     io_opentimeline_opentimelineio_UnknownSchema
 * Method:    getOriginalSchemaName
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_io_opentimeline_opentimelineio_UnknownSchema_getOriginalSchemaName
  (JNIEnv *, jobject);

/*
 * Class:     io_opentimeline_opentimelineio_UnknownSchema
 * Method:    getOriginalSchemaVersion
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_io_opentimeline_opentimelineio_UnknownSchema_getOriginalSchemaVersion
  (JNIEnv *, jobject);

/*
 * Class:     io_opentimeline_opentimelineio_UnknownSchema
 * Method:    isUnknownSchema
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_io_opentimeline_opentimelineio_UnknownSchema_isUnknownSchema
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
