/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_opentimeline_opentimelineio_ExternalReference */

#ifndef _Included_io_opentimeline_opentimelineio_ExternalReference
#define _Included_io_opentimeline_opentimelineio_ExternalReference
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io_opentimeline_opentimelineio_ExternalReference
 * Method:    initialize
 * Signature: (Ljava/lang/String;[DLio/opentimeline/opentimelineio/AnyDictionary;)V
 */
JNIEXPORT void JNICALL Java_io_opentimeline_opentimelineio_ExternalReference_initialize
  (JNIEnv *, jobject, jstring, jdoubleArray, jobject);

/*
 * Class:     io_opentimeline_opentimelineio_ExternalReference
 * Method:    getTargetURL
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_io_opentimeline_opentimelineio_ExternalReference_getTargetURL
  (JNIEnv *, jobject);

/*
 * Class:     io_opentimeline_opentimelineio_ExternalReference
 * Method:    setTargetURL
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_io_opentimeline_opentimelineio_ExternalReference_setTargetURL
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
