/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_opentimeline_opentimelineio_Deserialization */

#ifndef _Included_io_opentimeline_opentimelineio_Deserialization
#define _Included_io_opentimeline_opentimelineio_Deserialization
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io_opentimeline_opentimelineio_Deserialization
 * Method:    deserializeJSONFromString
 * Signature: (Ljava/lang/String;Lio/opentimeline/opentimelineio/Any;Lio/opentimeline/opentimelineio/ErrorStatus;)Z
 */
JNIEXPORT jboolean JNICALL Java_io_opentimeline_opentimelineio_Deserialization_deserializeJSONFromString
  (JNIEnv *, jobject, jstring, jobject, jobject);

/*
 * Class:     io_opentimeline_opentimelineio_Deserialization
 * Method:    deserializeJSONFromFile
 * Signature: (Ljava/lang/String;Lio/opentimeline/opentimelineio/Any;Lio/opentimeline/opentimelineio/ErrorStatus;)Z
 */
JNIEXPORT jboolean JNICALL Java_io_opentimeline_opentimelineio_Deserialization_deserializeJSONFromFile
  (JNIEnv *, jobject, jstring, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
