/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_opentimeline_opentimelineio_MediaReference */

#ifndef _Included_io_opentimeline_opentimelineio_MediaReference
#define _Included_io_opentimeline_opentimelineio_MediaReference
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io_opentimeline_opentimelineio_MediaReference
 * Method:    initialize
 * Signature: (Ljava/lang/String;[DLio/opentimeline/opentimelineio/AnyDictionary;)V
 */
JNIEXPORT void JNICALL Java_io_opentimeline_opentimelineio_MediaReference_initialize
  (JNIEnv *, jobject, jstring, jdoubleArray, jobject);

/*
 * Class:     io_opentimeline_opentimelineio_MediaReference
 * Method:    getAvailableRangeNative
 * Signature: ()[D
 */
JNIEXPORT jdoubleArray JNICALL Java_io_opentimeline_opentimelineio_MediaReference_getAvailableRangeNative
  (JNIEnv *, jobject);

/*
 * Class:     io_opentimeline_opentimelineio_MediaReference
 * Method:    setAvailableRangeNative
 * Signature: ([D)V
 */
JNIEXPORT void JNICALL Java_io_opentimeline_opentimelineio_MediaReference_setAvailableRangeNative
  (JNIEnv *, jobject, jdoubleArray);

/*
 * Class:     io_opentimeline_opentimelineio_MediaReference
 * Method:    isMissingReference
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_io_opentimeline_opentimelineio_MediaReference_isMissingReference
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
