/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_opentimeline_opentimelineio_Composable */

#ifndef _Included_io_opentimeline_opentimelineio_Composable
#define _Included_io_opentimeline_opentimelineio_Composable
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io_opentimeline_opentimelineio_Composable
 * Method:    initialize
 * Signature: (Ljava/lang/String;Lio/opentimeline/opentimelineio/AnyDictionary;)V
 */
JNIEXPORT void JNICALL Java_io_opentimeline_opentimelineio_Composable_initialize
  (JNIEnv *, jobject, jstring, jobject);

/*
 * Class:     io_opentimeline_opentimelineio_Composable
 * Method:    isVisible
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_io_opentimeline_opentimelineio_Composable_isVisible
  (JNIEnv *, jobject);

/*
 * Class:     io_opentimeline_opentimelineio_Composable
 * Method:    isOverlapping
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_io_opentimeline_opentimelineio_Composable_isOverlapping
  (JNIEnv *, jobject);

/*
 * Class:     io_opentimeline_opentimelineio_Composable
 * Method:    parent
 * Signature: ()Lio/opentimeline/opentimelineio/Composition;
 */
JNIEXPORT jobject JNICALL Java_io_opentimeline_opentimelineio_Composable_parent
  (JNIEnv *, jobject);

/*
 * Class:     io_opentimeline_opentimelineio_Composable
 * Method:    getDurationNative
 * Signature: (Lio/opentimeline/opentimelineio/ErrorStatus;)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_io_opentimeline_opentimelineio_Composable_getDurationNative
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
