/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_opentimeline_opentimelineio_FreezeFrame */

#ifndef _Included_io_opentimeline_opentimelineio_FreezeFrame
#define _Included_io_opentimeline_opentimelineio_FreezeFrame
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io_opentimeline_opentimelineio_FreezeFrame
 * Method:    initialize
 * Signature: (Ljava/lang/String;Lio/opentimeline/opentimelineio/AnyDictionary;)V
 */
JNIEXPORT void JNICALL Java_io_opentimeline_opentimelineio_FreezeFrame_initialize
  (JNIEnv *, jobject, jstring, jobject);

#ifdef __cplusplus
}
#endif
#endif
