/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_opentimeline_opentimelineio_OTIOTest */

#ifndef _Included_io_opentimeline_opentimelineio_OTIOTest
#define _Included_io_opentimeline_opentimelineio_OTIOTest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io_opentimeline_opentimelineio_OTIOTest
 * Method:    testRetainers1
 * Signature: (Lio/opentimeline/opentimelineio/SerializableCollection;)I
 */
JNIEXPORT jint JNICALL Java_io_opentimeline_opentimelineio_OTIOTest_testRetainers1
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
