/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_opentimeline_opentimelineio_Any */

#ifndef _Included_io_opentimeline_opentimelineio_Any
#define _Included_io_opentimeline_opentimelineio_Any
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io_opentimeline_opentimelineio_Any
 * Method:    initialize
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_io_opentimeline_opentimelineio_Any_initialize__Z
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     io_opentimeline_opentimelineio_Any
 * Method:    initialize
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_io_opentimeline_opentimelineio_Any_initialize__I
  (JNIEnv *, jobject, jint);

/*
 * Class:     io_opentimeline_opentimelineio_Any
 * Method:    initialize
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_io_opentimeline_opentimelineio_Any_initialize__D
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     io_opentimeline_opentimelineio_Any
 * Method:    initialize
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_io_opentimeline_opentimelineio_Any_initialize__Ljava_lang_String_2
  (JNIEnv *, jobject, jstring);

/*
 * Class:     io_opentimeline_opentimelineio_Any
 * Method:    safelyCastBoolean
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_io_opentimeline_opentimelineio_Any_safelyCastBoolean
  (JNIEnv *, jobject);

/*
 * Class:     io_opentimeline_opentimelineio_Any
 * Method:    safelyCastInt
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_io_opentimeline_opentimelineio_Any_safelyCastInt
  (JNIEnv *, jobject);

/*
 * Class:     io_opentimeline_opentimelineio_Any
 * Method:    safelyCastDouble
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_io_opentimeline_opentimelineio_Any_safelyCastDouble
  (JNIEnv *, jobject);

/*
 * Class:     io_opentimeline_opentimelineio_Any
 * Method:    safelyCastString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_io_opentimeline_opentimelineio_Any_safelyCastString
  (JNIEnv *, jobject);

/*
 * Class:     io_opentimeline_opentimelineio_Any
 * Method:    dispose
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_io_opentimeline_opentimelineio_Any_dispose
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
