/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_opentimeline_OTIOFinalizer */

#ifndef _Included_io_opentimeline_OTIOFinalizer
#define _Included_io_opentimeline_OTIOFinalizer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io_opentimeline_OTIOFinalizer
 * Method:    disposeNativeObject
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_io_opentimeline_OTIOFinalizer_disposeNativeObject
  (JNIEnv *, jobject, jlong, jstring);

#ifdef __cplusplus
}
#endif
#endif
