/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_opentimeline_opentimelineio_Effect */

#ifndef _Included_io_opentimeline_opentimelineio_Effect
#define _Included_io_opentimeline_opentimelineio_Effect
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io_opentimeline_opentimelineio_Effect
 * Method:    initialize
 * Signature: (Ljava/lang/String;Ljava/lang/String;Lio/opentimeline/opentimelineio/AnyDictionary;)V
 */
JNIEXPORT void JNICALL Java_io_opentimeline_opentimelineio_Effect_initialize
  (JNIEnv *, jobject, jstring, jstring, jobject);

/*
 * Class:     io_opentimeline_opentimelineio_Effect
 * Method:    getEffectName
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_io_opentimeline_opentimelineio_Effect_getEffectName
  (JNIEnv *, jobject);

/*
 * Class:     io_opentimeline_opentimelineio_Effect
 * Method:    setEffectName
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_io_opentimeline_opentimelineio_Effect_setEffectName
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
