/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_opentimeline_opentime_TimeTransform */

#ifndef _Included_io_opentimeline_opentime_TimeTransform
#define _Included_io_opentimeline_opentime_TimeTransform
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io_opentimeline_opentime_TimeTransform
 * Method:    appliedTo
 * Signature: (Lio/opentimeline/opentime/TimeRange;)Lio/opentimeline/opentime/TimeRange;
 */
JNIEXPORT jobject JNICALL Java_io_opentimeline_opentime_TimeTransform_appliedTo__Lio_opentimeline_opentime_TimeRange_2
  (JNIEnv *, jobject, jobject);

/*
 * Class:     io_opentimeline_opentime_TimeTransform
 * Method:    appliedTo
 * Signature: (Lio/opentimeline/opentime/TimeTransform;)Lio/opentimeline/opentime/TimeTransform;
 */
JNIEXPORT jobject JNICALL Java_io_opentimeline_opentime_TimeTransform_appliedTo__Lio_opentimeline_opentime_TimeTransform_2
  (JNIEnv *, jobject, jobject);

/*
 * Class:     io_opentimeline_opentime_TimeTransform
 * Method:    appliedTo
 * Signature: (Lio/opentimeline/opentime/RationalTime;)Lio/opentimeline/opentime/RationalTime;
 */
JNIEXPORT jobject JNICALL Java_io_opentimeline_opentime_TimeTransform_appliedTo__Lio_opentimeline_opentime_RationalTime_2
  (JNIEnv *, jobject, jobject);

/*
 * Class:     io_opentimeline_opentime_TimeTransform
 * Method:    equals
 * Signature: (Lio/opentimeline/opentime/TimeTransform;)Z
 */
JNIEXPORT jboolean JNICALL Java_io_opentimeline_opentime_TimeTransform_equals
  (JNIEnv *, jobject, jobject);

/*
 * Class:     io_opentimeline_opentime_TimeTransform
 * Method:    notEquals
 * Signature: (Lio/opentimeline/opentime/TimeTransform;)Z
 */
JNIEXPORT jboolean JNICALL Java_io_opentimeline_opentime_TimeTransform_notEquals
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
