/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_opentimeline_opentimelineio_Marker */

#ifndef _Included_io_opentimeline_opentimelineio_Marker
#define _Included_io_opentimeline_opentimelineio_Marker
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io_opentimeline_opentimelineio_Marker
 * Method:    initialize
 * Signature: (Ljava/lang/String;Lio/opentimeline/opentime/TimeRange;Ljava/lang/String;Lio/opentimeline/opentimelineio/AnyDictionary;)V
 */
JNIEXPORT void JNICALL Java_io_opentimeline_opentimelineio_Marker_initialize
  (JNIEnv *, jobject, jstring, jobject, jstring, jobject);

/*
 * Class:     io_opentimeline_opentimelineio_Marker
 * Method:    getColor
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_io_opentimeline_opentimelineio_Marker_getColor
  (JNIEnv *, jobject);

/*
 * Class:     io_opentimeline_opentimelineio_Marker
 * Method:    setColor
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_io_opentimeline_opentimelineio_Marker_setColor
  (JNIEnv *, jobject, jstring);

/*
 * Class:     io_opentimeline_opentimelineio_Marker
 * Method:    getMarkedRange
 * Signature: ()Lio/opentimeline/opentime/TimeRange;
 */
JNIEXPORT jobject JNICALL Java_io_opentimeline_opentimelineio_Marker_getMarkedRange
  (JNIEnv *, jobject);

/*
 * Class:     io_opentimeline_opentimelineio_Marker
 * Method:    setMarkedRange
 * Signature: (Lio/opentimeline/opentime/TimeRange;)V
 */
JNIEXPORT void JNICALL Java_io_opentimeline_opentimelineio_Marker_setMarkedRange
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
