/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_opentimeline_opentimelineio_Any */

#ifndef _Included_io_opentimeline_opentimelineio_Any
#define _Included_io_opentimeline_opentimelineio_Any
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io_opentimeline_opentimelineio_Any
 * Method:    initializeBool
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_io_opentimeline_opentimelineio_Any_initializeBool
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     io_opentimeline_opentimelineio_Any
 * Method:    initializeInt
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_io_opentimeline_opentimelineio_Any_initializeInt
  (JNIEnv *, jobject, jint);

/*
 * Class:     io_opentimeline_opentimelineio_Any
 * Method:    initializeDouble
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_io_opentimeline_opentimelineio_Any_initializeDouble
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     io_opentimeline_opentimelineio_Any
 * Method:    initializeString
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_io_opentimeline_opentimelineio_Any_initializeString
  (JNIEnv *, jobject, jstring);

/*
 * Class:     io_opentimeline_opentimelineio_Any
 * Method:    initializeRationalTime
 * Signature: ([D)V
 */
JNIEXPORT void JNICALL Java_io_opentimeline_opentimelineio_Any_initializeRationalTime
  (JNIEnv *, jobject, jdoubleArray);

/*
 * Class:     io_opentimeline_opentimelineio_Any
 * Method:    initializeTimeRange
 * Signature: ([D)V
 */
JNIEXPORT void JNICALL Java_io_opentimeline_opentimelineio_Any_initializeTimeRange
  (JNIEnv *, jobject, jdoubleArray);

/*
 * Class:     io_opentimeline_opentimelineio_Any
 * Method:    initializeTimeTransform
 * Signature: ([D)V
 */
JNIEXPORT void JNICALL Java_io_opentimeline_opentimelineio_Any_initializeTimeTransform
  (JNIEnv *, jobject, jdoubleArray);

/*
 * Class:     io_opentimeline_opentimelineio_Any
 * Method:    initializeAnyVector
 * Signature: (Lio/opentimeline/opentimelineio/AnyVector;)V
 */
JNIEXPORT void JNICALL Java_io_opentimeline_opentimelineio_Any_initializeAnyVector
  (JNIEnv *, jobject, jobject);

/*
 * Class:     io_opentimeline_opentimelineio_Any
 * Method:    initializeAnyDictionary
 * Signature: (Lio/opentimeline/opentimelineio/AnyDictionary;)V
 */
JNIEXPORT void JNICALL Java_io_opentimeline_opentimelineio_Any_initializeAnyDictionary
  (JNIEnv *, jobject, jobject);

/*
 * Class:     io_opentimeline_opentimelineio_Any
 * Method:    initializeSerializableObject
 * Signature: (Lio/opentimeline/opentimelineio/SerializableObject;)V
 */
JNIEXPORT void JNICALL Java_io_opentimeline_opentimelineio_Any_initializeSerializableObject
  (JNIEnv *, jobject, jobject);

/*
 * Class:     io_opentimeline_opentimelineio_Any
 * Method:    safelyCastBoolean
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_io_opentimeline_opentimelineio_Any_safelyCastBoolean
  (JNIEnv *, jobject);

/*
 * Class:     io_opentimeline_opentimelineio_Any
 * Method:    safelyCastInt
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_io_opentimeline_opentimelineio_Any_safelyCastInt
  (JNIEnv *, jobject);

/*
 * Class:     io_opentimeline_opentimelineio_Any
 * Method:    safelyCastDouble
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_io_opentimeline_opentimelineio_Any_safelyCastDouble
  (JNIEnv *, jobject);

/*
 * Class:     io_opentimeline_opentimelineio_Any
 * Method:    safelyCastString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_io_opentimeline_opentimelineio_Any_safelyCastString
  (JNIEnv *, jobject);

/*
 * Class:     io_opentimeline_opentimelineio_Any
 * Method:    safelyCastRationalTimeNative
 * Signature: ()[D
 */
JNIEXPORT jdoubleArray JNICALL Java_io_opentimeline_opentimelineio_Any_safelyCastRationalTimeNative
  (JNIEnv *, jobject);

/*
 * Class:     io_opentimeline_opentimelineio_Any
 * Method:    safelyCastTimeRangeNative
 * Signature: ()[D
 */
JNIEXPORT jdoubleArray JNICALL Java_io_opentimeline_opentimelineio_Any_safelyCastTimeRangeNative
  (JNIEnv *, jobject);

/*
 * Class:     io_opentimeline_opentimelineio_Any
 * Method:    safelyCastTimeTransformNative
 * Signature: ()[D
 */
JNIEXPORT jdoubleArray JNICALL Java_io_opentimeline_opentimelineio_Any_safelyCastTimeTransformNative
  (JNIEnv *, jobject);

/*
 * Class:     io_opentimeline_opentimelineio_Any
 * Method:    safelyCastSerializableObject
 * Signature: ()Lio/opentimeline/opentimelineio/SerializableObject;
 */
JNIEXPORT jobject JNICALL Java_io_opentimeline_opentimelineio_Any_safelyCastSerializableObject
  (JNIEnv *, jobject);

/*
 * Class:     io_opentimeline_opentimelineio_Any
 * Method:    safelyCastAnyDictionary
 * Signature: ()Lio/opentimeline/opentimelineio/AnyDictionary;
 */
JNIEXPORT jobject JNICALL Java_io_opentimeline_opentimelineio_Any_safelyCastAnyDictionary
  (JNIEnv *, jobject);

/*
 * Class:     io_opentimeline_opentimelineio_Any
 * Method:    safelyCastAnyVector
 * Signature: ()Lio/opentimeline/opentimelineio/AnyVector;
 */
JNIEXPORT jobject JNICALL Java_io_opentimeline_opentimelineio_Any_safelyCastAnyVector
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
