/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_opentimeline_opentime_TimeTransform */

#ifndef _Included_io_opentimeline_opentime_TimeTransform
#define _Included_io_opentimeline_opentime_TimeTransform
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io_opentimeline_opentime_TimeTransform
 * Method:    appliedToTimeRangeNative
 * Signature: ([D[D)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_io_opentimeline_opentime_TimeTransform_appliedToTimeRangeNative
  (JNIEnv *, jclass, jdoubleArray, jdoubleArray);

/*
 * Class:     io_opentimeline_opentime_TimeTransform
 * Method:    appliedToTimeTransformNative
 * Signature: ([D[D)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_io_opentimeline_opentime_TimeTransform_appliedToTimeTransformNative
  (JNIEnv *, jclass, jdoubleArray, jdoubleArray);

/*
 * Class:     io_opentimeline_opentime_TimeTransform
 * Method:    appliedToRationalTimeNative
 * Signature: ([D[D)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_io_opentimeline_opentime_TimeTransform_appliedToRationalTimeNative
  (JNIEnv *, jclass, jdoubleArray, jdoubleArray);

/*
 * Class:     io_opentimeline_opentime_TimeTransform
 * Method:    equalsNative
 * Signature: ([D[D)Z
 */
JNIEXPORT jboolean JNICALL Java_io_opentimeline_opentime_TimeTransform_equalsNative
  (JNIEnv *, jclass, jdoubleArray, jdoubleArray);

/*
 * Class:     io_opentimeline_opentime_TimeTransform
 * Method:    notEqualsNative
 * Signature: ([D[D)Z
 */
JNIEXPORT jboolean JNICALL Java_io_opentimeline_opentime_TimeTransform_notEqualsNative
  (JNIEnv *, jclass, jdoubleArray, jdoubleArray);

#ifdef __cplusplus
}
#endif
#endif
