/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_opentimeline_opentimelineio_Clip */

#ifndef _Included_io_opentimeline_opentimelineio_Clip
#define _Included_io_opentimeline_opentimelineio_Clip
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io_opentimeline_opentimelineio_Clip
 * Method:    initialize
 * Signature: (Ljava/lang/String;Lio/opentimeline/opentimelineio/MediaReference;Lio/opentimeline/opentime/TimeRange;Lio/opentimeline/opentimelineio/AnyDictionary;)V
 */
JNIEXPORT void JNICALL Java_io_opentimeline_opentimelineio_Clip_initialize
  (JNIEnv *, jobject, jstring, jobject, jobject, jobject);

/*
 * Class:     io_opentimeline_opentimelineio_Clip
 * Method:    setMediaReference
 * Signature: (Lio/opentimeline/opentimelineio/MediaReference;)V
 */
JNIEXPORT void JNICALL Java_io_opentimeline_opentimelineio_Clip_setMediaReference
  (JNIEnv *, jobject, jobject);

/*
 * Class:     io_opentimeline_opentimelineio_Clip
 * Method:    getMediaReference
 * Signature: ()Lio/opentimeline/opentimelineio/MediaReference;
 */
JNIEXPORT jobject JNICALL Java_io_opentimeline_opentimelineio_Clip_getMediaReference
  (JNIEnv *, jobject);

/*
 * Class:     io_opentimeline_opentimelineio_Clip
 * Method:    getAvailableRange
 * Signature: (Lio/opentimeline/opentimelineio/ErrorStatus;)Lio/opentimeline/opentime/TimeRange;
 */
JNIEXPORT jobject JNICALL Java_io_opentimeline_opentimelineio_Clip_getAvailableRange
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
