/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_opentimeline_opentimelineio_AnyVector_Iterator */

#ifndef _Included_io_opentimeline_opentimelineio_AnyVector_Iterator
#define _Included_io_opentimeline_opentimelineio_AnyVector_Iterator
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io_opentimeline_opentimelineio_AnyVector_Iterator
 * Method:    initialize
 * Signature: (Lio/opentimeline/opentimelineio/AnyVector;)V
 */
JNIEXPORT void JNICALL Java_io_opentimeline_opentimelineio_AnyVector_00024Iterator_initialize
  (JNIEnv *, jobject, jobject);

/*
 * Class:     io_opentimeline_opentimelineio_AnyVector_Iterator
 * Method:    nextNative
 * Signature: (Lio/opentimeline/opentimelineio/AnyVector;)Lio/opentimeline/opentimelineio/Any;
 */
JNIEXPORT jobject JNICALL Java_io_opentimeline_opentimelineio_AnyVector_00024Iterator_nextNative
  (JNIEnv *, jobject, jobject);

/*
 * Class:     io_opentimeline_opentimelineio_AnyVector_Iterator
 * Method:    previousNative
 * Signature: (Lio/opentimeline/opentimelineio/AnyVector;)Lio/opentimeline/opentimelineio/Any;
 */
JNIEXPORT jobject JNICALL Java_io_opentimeline_opentimelineio_AnyVector_00024Iterator_previousNative
  (JNIEnv *, jobject, jobject);

/*
 * Class:     io_opentimeline_opentimelineio_AnyVector_Iterator
 * Method:    hasNextNative
 * Signature: (Lio/opentimeline/opentimelineio/AnyVector;)Z
 */
JNIEXPORT jboolean JNICALL Java_io_opentimeline_opentimelineio_AnyVector_00024Iterator_hasNextNative
  (JNIEnv *, jobject, jobject);

/*
 * Class:     io_opentimeline_opentimelineio_AnyVector_Iterator
 * Method:    hasPreviousNative
 * Signature: (Lio/opentimeline/opentimelineio/AnyVector;)Z
 */
JNIEXPORT jboolean JNICALL Java_io_opentimeline_opentimelineio_AnyVector_00024Iterator_hasPreviousNative
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
