/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_opentimeline_opentimelineio_SerializableObjectWithMetadata */

#ifndef _Included_io_opentimeline_opentimelineio_SerializableObjectWithMetadata
#define _Included_io_opentimeline_opentimelineio_SerializableObjectWithMetadata
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io_opentimeline_opentimelineio_SerializableObjectWithMetadata
 * Method:    initialize
 * Signature: (Ljava/lang/String;Lio/opentimeline/opentimelineio/AnyDictionary;)V
 */
JNIEXPORT void JNICALL Java_io_opentimeline_opentimelineio_SerializableObjectWithMetadata_initialize
  (JNIEnv *, jobject, jstring, jobject);

/*
 * Class:     io_opentimeline_opentimelineio_SerializableObjectWithMetadata
 * Method:    getName
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_io_opentimeline_opentimelineio_SerializableObjectWithMetadata_getName
  (JNIEnv *, jobject);

/*
 * Class:     io_opentimeline_opentimelineio_SerializableObjectWithMetadata
 * Method:    setName
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_io_opentimeline_opentimelineio_SerializableObjectWithMetadata_setName
  (JNIEnv *, jobject, jstring);

/*
 * Class:     io_opentimeline_opentimelineio_SerializableObjectWithMetadata
 * Method:    getMetadata
 * Signature: ()Lio/opentimeline/opentimelineio/AnyDictionary;
 */
JNIEXPORT jobject JNICALL Java_io_opentimeline_opentimelineio_SerializableObjectWithMetadata_getMetadata
  (JNIEnv *, jobject);

/*
 * Class:     io_opentimeline_opentimelineio_SerializableObjectWithMetadata
 * Method:    setMetadata
 * Signature: (Lio/opentimeline/opentimelineio/AnyDictionary;)V
 */
JNIEXPORT void JNICALL Java_io_opentimeline_opentimelineio_SerializableObjectWithMetadata_setMetadata
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
