/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_opentimeline_opentimelineio_Item */

#ifndef _Included_io_opentimeline_opentimelineio_Item
#define _Included_io_opentimeline_opentimelineio_Item
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io_opentimeline_opentimelineio_Item
 * Method:    initialize
 * Signature: (Ljava/lang/String;[DLio/opentimeline/opentimelineio/AnyDictionary;[Lio/opentimeline/opentimelineio/Effect;[Lio/opentimeline/opentimelineio/Marker;)V
 */
JNIEXPORT void JNICALL Java_io_opentimeline_opentimelineio_Item_initialize
  (JNIEnv *, jobject, jstring, jdoubleArray, jobject, jobjectArray, jobjectArray);

/*
 * Class:     io_opentimeline_opentimelineio_Item
 * Method:    isVisible
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_io_opentimeline_opentimelineio_Item_isVisible
  (JNIEnv *, jobject);

/*
 * Class:     io_opentimeline_opentimelineio_Item
 * Method:    isOverlapping
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_io_opentimeline_opentimelineio_Item_isOverlapping
  (JNIEnv *, jobject);

/*
 * Class:     io_opentimeline_opentimelineio_Item
 * Method:    getSourceRangeNative
 * Signature: ()[D
 */
JNIEXPORT jdoubleArray JNICALL Java_io_opentimeline_opentimelineio_Item_getSourceRangeNative
  (JNIEnv *, jobject);

/*
 * Class:     io_opentimeline_opentimelineio_Item
 * Method:    setSourceRangeNative
 * Signature: ([D)V
 */
JNIEXPORT void JNICALL Java_io_opentimeline_opentimelineio_Item_setSourceRangeNative
  (JNIEnv *, jobject, jdoubleArray);

/*
 * Class:     io_opentimeline_opentimelineio_Item
 * Method:    getEffectsNative
 * Signature: ()[Lio/opentimeline/opentimelineio/SerializableObject/Retainer;
 */
JNIEXPORT jobjectArray JNICALL Java_io_opentimeline_opentimelineio_Item_getEffectsNative
  (JNIEnv *, jobject);

/*
 * Class:     io_opentimeline_opentimelineio_Item
 * Method:    getMarkersNative
 * Signature: ()[Lio/opentimeline/opentimelineio/SerializableObject/Retainer;
 */
JNIEXPORT jobjectArray JNICALL Java_io_opentimeline_opentimelineio_Item_getMarkersNative
  (JNIEnv *, jobject);

/*
 * Class:     io_opentimeline_opentimelineio_Item
 * Method:    getDurationNative
 * Signature: (Lio/opentimeline/opentimelineio/ErrorStatus;)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_io_opentimeline_opentimelineio_Item_getDurationNative
  (JNIEnv *, jobject, jobject);

/*
 * Class:     io_opentimeline_opentimelineio_Item
 * Method:    getAvailableRangeNative
 * Signature: (Lio/opentimeline/opentimelineio/ErrorStatus;)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_io_opentimeline_opentimelineio_Item_getAvailableRangeNative
  (JNIEnv *, jobject, jobject);

/*
 * Class:     io_opentimeline_opentimelineio_Item
 * Method:    getTrimmedRangeNative
 * Signature: (Lio/opentimeline/opentimelineio/ErrorStatus;)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_io_opentimeline_opentimelineio_Item_getTrimmedRangeNative
  (JNIEnv *, jobject, jobject);

/*
 * Class:     io_opentimeline_opentimelineio_Item
 * Method:    getVisibleRangeNative
 * Signature: (Lio/opentimeline/opentimelineio/ErrorStatus;)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_io_opentimeline_opentimelineio_Item_getVisibleRangeNative
  (JNIEnv *, jobject, jobject);

/*
 * Class:     io_opentimeline_opentimelineio_Item
 * Method:    getTrimmedRangeInParentNative
 * Signature: (Lio/opentimeline/opentimelineio/ErrorStatus;)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_io_opentimeline_opentimelineio_Item_getTrimmedRangeInParentNative
  (JNIEnv *, jobject, jobject);

/*
 * Class:     io_opentimeline_opentimelineio_Item
 * Method:    getRangeInParentNative
 * Signature: (Lio/opentimeline/opentimelineio/ErrorStatus;)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_io_opentimeline_opentimelineio_Item_getRangeInParentNative
  (JNIEnv *, jobject, jobject);

/*
 * Class:     io_opentimeline_opentimelineio_Item
 * Method:    getTransformedTimeNative
 * Signature: ([DLio/opentimeline/opentimelineio/Item;Lio/opentimeline/opentimelineio/ErrorStatus;)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_io_opentimeline_opentimelineio_Item_getTransformedTimeNative
  (JNIEnv *, jobject, jdoubleArray, jobject, jobject);

/*
 * Class:     io_opentimeline_opentimelineio_Item
 * Method:    getTransformedTimeRangeNative
 * Signature: ([DLio/opentimeline/opentimelineio/Item;Lio/opentimeline/opentimelineio/ErrorStatus;)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_io_opentimeline_opentimelineio_Item_getTransformedTimeRangeNative
  (JNIEnv *, jobject, jdoubleArray, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
