/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_opentimeline_opentime_ErrorStatus */

#ifndef _Included_io_opentimeline_opentime_ErrorStatus
#define _Included_io_opentimeline_opentime_ErrorStatus
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io_opentimeline_opentime_ErrorStatus
 * Method:    initialize
 * Signature: (ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_io_opentimeline_opentime_ErrorStatus_initialize
  (JNIEnv *, jobject, jint, jstring);

/*
 * Class:     io_opentimeline_opentime_ErrorStatus
 * Method:    outcomeToStringNative
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_io_opentimeline_opentime_ErrorStatus_outcomeToStringNative
  (JNIEnv *, jclass, jint);

/*
 * Class:     io_opentimeline_opentime_ErrorStatus
 * Method:    getOutcomeNative
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_io_opentimeline_opentime_ErrorStatus_getOutcomeNative
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
