/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_opentimeline_opentimelineio_SerializableObject_Retainer */

#ifndef _Included_io_opentimeline_opentimelineio_SerializableObject_Retainer
#define _Included_io_opentimeline_opentimelineio_SerializableObject_Retainer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io_opentimeline_opentimelineio_SerializableObject_Retainer
 * Method:    initialize
 * Signature: (Lio/opentimeline/opentimelineio/SerializableObject;)V
 */
JNIEXPORT void JNICALL Java_io_opentimeline_opentimelineio_SerializableObject_00024Retainer_initialize
  (JNIEnv *, jobject, jobject);

/*
 * Class:     io_opentimeline_opentimelineio_SerializableObject_Retainer
 * Method:    value
 * Signature: ()Lio/opentimeline/opentimelineio/SerializableObject;
 */
JNIEXPORT jobject JNICALL Java_io_opentimeline_opentimelineio_SerializableObject_00024Retainer_value
  (JNIEnv *, jobject);

/*
 * Class:     io_opentimeline_opentimelineio_SerializableObject_Retainer
 * Method:    takeValue
 * Signature: ()Lio/opentimeline/opentimelineio/SerializableObject;
 */
JNIEXPORT jobject JNICALL Java_io_opentimeline_opentimelineio_SerializableObject_00024Retainer_takeValue
  (JNIEnv *, jobject);

/*
 * Class:     io_opentimeline_opentimelineio_SerializableObject_Retainer
 * Method:    dispose
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_io_opentimeline_opentimelineio_SerializableObject_00024Retainer_dispose
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
