/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_opentimeline_opentimelineio_AnyDictionary_Iterator */

#ifndef _Included_io_opentimeline_opentimelineio_AnyDictionary_Iterator
#define _Included_io_opentimeline_opentimelineio_AnyDictionary_Iterator
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io_opentimeline_opentimelineio_AnyDictionary_Iterator
 * Method:    initialize
 * Signature: (Lio/opentimeline/opentimelineio/AnyDictionary;)V
 */
JNIEXPORT void JNICALL Java_io_opentimeline_opentimelineio_AnyDictionary_00024Iterator_initialize
  (JNIEnv *, jobject, jobject);

/*
 * Class:     io_opentimeline_opentimelineio_AnyDictionary_Iterator
 * Method:    nextNative
 * Signature: ()Lio/opentimeline/opentimelineio/AnyDictionary/Iterator;
 */
JNIEXPORT jobject JNICALL Java_io_opentimeline_opentimelineio_AnyDictionary_00024Iterator_nextNative
  (JNIEnv *, jobject);

/*
 * Class:     io_opentimeline_opentimelineio_AnyDictionary_Iterator
 * Method:    previousNative
 * Signature: ()Lio/opentimeline/opentimelineio/AnyDictionary/Iterator;
 */
JNIEXPORT jobject JNICALL Java_io_opentimeline_opentimelineio_AnyDictionary_00024Iterator_previousNative
  (JNIEnv *, jobject);

/*
 * Class:     io_opentimeline_opentimelineio_AnyDictionary_Iterator
 * Method:    hasNextNative
 * Signature: (Lio/opentimeline/opentimelineio/AnyDictionary;)Z
 */
JNIEXPORT jboolean JNICALL Java_io_opentimeline_opentimelineio_AnyDictionary_00024Iterator_hasNextNative
  (JNIEnv *, jobject, jobject);

/*
 * Class:     io_opentimeline_opentimelineio_AnyDictionary_Iterator
 * Method:    hasPreviousNative
 * Signature: (Lio/opentimeline/opentimelineio/AnyDictionary;)Z
 */
JNIEXPORT jboolean JNICALL Java_io_opentimeline_opentimelineio_AnyDictionary_00024Iterator_hasPreviousNative
  (JNIEnv *, jobject, jobject);

/*
 * Class:     io_opentimeline_opentimelineio_AnyDictionary_Iterator
 * Method:    getKey
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_io_opentimeline_opentimelineio_AnyDictionary_00024Iterator_getKey
  (JNIEnv *, jobject);

/*
 * Class:     io_opentimeline_opentimelineio_AnyDictionary_Iterator
 * Method:    getValue
 * Signature: ()Lio/opentimeline/opentimelineio/Any;
 */
JNIEXPORT jobject JNICALL Java_io_opentimeline_opentimelineio_AnyDictionary_00024Iterator_getValue
  (JNIEnv *, jobject);

/*
 * Class:     io_opentimeline_opentimelineio_AnyDictionary_Iterator
 * Method:    dispose
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_io_opentimeline_opentimelineio_AnyDictionary_00024Iterator_dispose
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
