/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_opentimeline_opentimelineio_SerializableObject */

#ifndef _Included_io_opentimeline_opentimelineio_SerializableObject
#define _Included_io_opentimeline_opentimelineio_SerializableObject
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io_opentimeline_opentimelineio_SerializableObject
 * Method:    initialize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_io_opentimeline_opentimelineio_SerializableObject_initialize
  (JNIEnv *, jobject);

/*
 * Class:     io_opentimeline_opentimelineio_SerializableObject
 * Method:    toJSONFile
 * Signature: (Ljava/lang/String;Lio/opentimeline/opentimelineio/ErrorStatus;)Z
 */
JNIEXPORT jboolean JNICALL Java_io_opentimeline_opentimelineio_SerializableObject_toJSONFile__Ljava_lang_String_2Lio_opentimeline_opentimelineio_ErrorStatus_2
  (JNIEnv *, jobject, jstring, jobject);

/*
 * Class:     io_opentimeline_opentimelineio_SerializableObject
 * Method:    toJSONFile
 * Signature: (Ljava/lang/String;Lio/opentimeline/opentimelineio/ErrorStatus;I)Z
 */
JNIEXPORT jboolean JNICALL Java_io_opentimeline_opentimelineio_SerializableObject_toJSONFile__Ljava_lang_String_2Lio_opentimeline_opentimelineio_ErrorStatus_2I
  (JNIEnv *, jobject, jstring, jobject, jint);

/*
 * Class:     io_opentimeline_opentimelineio_SerializableObject
 * Method:    toJSONString
 * Signature: (Lio/opentimeline/opentimelineio/ErrorStatus;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_io_opentimeline_opentimelineio_SerializableObject_toJSONString__Lio_opentimeline_opentimelineio_ErrorStatus_2
  (JNIEnv *, jobject, jobject);

/*
 * Class:     io_opentimeline_opentimelineio_SerializableObject
 * Method:    toJSONString
 * Signature: (Lio/opentimeline/opentimelineio/ErrorStatus;I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_io_opentimeline_opentimelineio_SerializableObject_toJSONString__Lio_opentimeline_opentimelineio_ErrorStatus_2I
  (JNIEnv *, jobject, jobject, jint);

/*
 * Class:     io_opentimeline_opentimelineio_SerializableObject
 * Method:    fromJSONFile
 * Signature: (Ljava/lang/String;Lio/opentimeline/opentimelineio/ErrorStatus;)Lio/opentimeline/opentimelineio/SerializableObject;
 */
JNIEXPORT jobject JNICALL Java_io_opentimeline_opentimelineio_SerializableObject_fromJSONFile
  (JNIEnv *, jclass, jstring, jobject);

/*
 * Class:     io_opentimeline_opentimelineio_SerializableObject
 * Method:    fromJSONString
 * Signature: (Ljava/lang/String;Lio/opentimeline/opentimelineio/ErrorStatus;)Lio/opentimeline/opentimelineio/SerializableObject;
 */
JNIEXPORT jobject JNICALL Java_io_opentimeline_opentimelineio_SerializableObject_fromJSONString
  (JNIEnv *, jclass, jstring, jobject);

/*
 * Class:     io_opentimeline_opentimelineio_SerializableObject
 * Method:    isEquivalentTo
 * Signature: (Lio/opentimeline/opentimelineio/SerializableObject;)Z
 */
JNIEXPORT jboolean JNICALL Java_io_opentimeline_opentimelineio_SerializableObject_isEquivalentTo
  (JNIEnv *, jobject, jobject);

/*
 * Class:     io_opentimeline_opentimelineio_SerializableObject
 * Method:    clone
 * Signature: (Lio/opentimeline/opentimelineio/ErrorStatus;)Lio/opentimeline/opentimelineio/SerializableObject;
 */
JNIEXPORT jobject JNICALL Java_io_opentimeline_opentimelineio_SerializableObject_clone
  (JNIEnv *, jobject, jobject);

/*
 * Class:     io_opentimeline_opentimelineio_SerializableObject
 * Method:    dynamicFields
 * Signature: ()Lio/opentimeline/opentimelineio/AnyDictionary;
 */
JNIEXPORT jobject JNICALL Java_io_opentimeline_opentimelineio_SerializableObject_dynamicFields
  (JNIEnv *, jobject);

/*
 * Class:     io_opentimeline_opentimelineio_SerializableObject
 * Method:    isUnknownSchema
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_io_opentimeline_opentimelineio_SerializableObject_isUnknownSchema
  (JNIEnv *, jobject);

/*
 * Class:     io_opentimeline_opentimelineio_SerializableObject
 * Method:    schemaName
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_io_opentimeline_opentimelineio_SerializableObject_schemaName
  (JNIEnv *, jobject);

/*
 * Class:     io_opentimeline_opentimelineio_SerializableObject
 * Method:    schemaVersion
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_io_opentimeline_opentimelineio_SerializableObject_schemaVersion
  (JNIEnv *, jobject);

/*
 * Class:     io_opentimeline_opentimelineio_SerializableObject
 * Method:    currentRefCount
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_io_opentimeline_opentimelineio_SerializableObject_currentRefCount
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
