/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_opentimeline_opentimelineio_GeneratorReference */

#ifndef _Included_io_opentimeline_opentimelineio_GeneratorReference
#define _Included_io_opentimeline_opentimelineio_GeneratorReference
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io_opentimeline_opentimelineio_GeneratorReference
 * Method:    initialize
 * Signature: (Ljava/lang/String;Ljava/lang/String;[DLio/opentimeline/opentimelineio/AnyDictionary;Lio/opentimeline/opentimelineio/AnyDictionary;)V
 */
JNIEXPORT void JNICALL Java_io_opentimeline_opentimelineio_GeneratorReference_initialize
  (JNIEnv *, jobject, jstring, jstring, jdoubleArray, jobject, jobject);

/*
 * Class:     io_opentimeline_opentimelineio_GeneratorReference
 * Method:    getGeneratorKind
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_io_opentimeline_opentimelineio_GeneratorReference_getGeneratorKind
  (JNIEnv *, jobject);

/*
 * Class:     io_opentimeline_opentimelineio_GeneratorReference
 * Method:    setGeneratorKind
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_io_opentimeline_opentimelineio_GeneratorReference_setGeneratorKind
  (JNIEnv *, jobject, jstring);

/*
 * Class:     io_opentimeline_opentimelineio_GeneratorReference
 * Method:    getParameters
 * Signature: ()Lio/opentimeline/opentimelineio/AnyDictionary;
 */
JNIEXPORT jobject JNICALL Java_io_opentimeline_opentimelineio_GeneratorReference_getParameters
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
